# Generated by Django 3.2.16 on 2022-12-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausepermission',
            name='requires_disease_restriction',
        ),
        migrations.AddField(
            model_name='datausepermission',
            name='requires_disease_term',
            field=models.BooleanField(default=False, help_text='Indicator of whether an additional disease term is required for this term.'),
        ),
    ]
