# Generated by Django 3.2.16 on 2022-12-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datausepermission',
            name='abbreviation',
            field=models.CharField(help_text='The short code for this consent group (e.g., GRU).', max_length=15),
        ),
        migrations.AlterField(
            model_name='datausepermission',
            name='term',
            field=models.CharField(help_text='The term associated this instance (e.g., general research use).', max_length=255),
        ),
    ]
