# Generated by Django 3.2.13 on 2022-09-06 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anvil_consortium_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataUsePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=31, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.CreateModel(
            name='dbGaPWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_consent_code', models.CharField(max_length=63)),
                ('data_use_limitations', models.TextField()),
                ('phs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('participant_set', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_use_modifiers', models.ManyToManyField(blank=True, to='primed_anvil.DataUseModifier')),
                ('data_use_permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.datausepermission')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.study')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': ' dbGaP workspace',
                'verbose_name_plural': ' dbGaP workspaces',
            },
        ),
        migrations.AddConstraint(
            model_name='dbgapworkspace',
            constraint=models.UniqueConstraint(fields=('study', 'phs', 'version'), name='unique_dbgap_workspace'),
        ),
    ]
