# Generated by Django 3.2.13 on 2022-09-28 16:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(help_text='The short code for this modifier (e.g., NPU).', max_length=15, unique=True)),
                ('description', models.CharField(help_text='The description of this modifier (e.g., Non-Profit Use only).', max_length=255, unique=True)),
                ('identifier', models.CharField(help_text='The identifier of this modifier (e.g., DUO:0000045).', max_length=31, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataUsePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(help_text='The short code for this consent group (e.g., GRU).', max_length=15, unique=True)),
                ('description', models.CharField(help_text='The description for this consent group (e.g., General Research Use).', max_length=255, unique=True)),
                ('identifier', models.CharField(help_text='The identifier of this consent group (e.g., DUO:0000045).', max_length=31, unique=True)),
                ('requires_disease_restriction', models.BooleanField(default=False, help_text='Indicator of whether an additional disease restriction is required for this term.')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('short_name', models.CharField(help_text='The short name for this Study.', max_length=31, unique=True)),
                ('full_name', models.CharField(help_text='The full name for this Study.', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'studies',
            },
        ),
    ]
