# Generated by Django 3.2.13 on 2022-08-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataUsePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyConsentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_consent_code', models.CharField(max_length=63)),
                ('data_use_limitations', models.TextField()),
                ('data_use_modifiers', models.ManyToManyField(to='primed_anvil.DataUseModifier')),
                ('data_use_permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.datausepermission')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.study')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studyconsentgroup',
            constraint=models.UniqueConstraint(fields=('study', 'full_consent_code'), name='unique_study_consent_group'),
        ),
    ]
