# Generated by Django 3.2.13 on 2022-09-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausepermission',
            name='requires_disease_restriction',
            field=models.BooleanField(default=False, help_text='Indicator of whether an additional disease restriction is required for this term.'),
        ),
        migrations.AddField(
            model_name='dbgapworkspace',
            name='disease_restriction',
            field=models.CharField(blank=True, help_text='The disease restriction if required by data_use_permission.', max_length=255, null=True),
        ),
    ]
