# Generated by Django 3.2.13 on 2022-08-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySite',
        ),
    ]
