# Generated by Django 3.2.13 on 2022-08-23 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0011_workspace_workspacedatatype'),
        ('primed_anvil', '0002_datausepermission_datausemodifier_studyconsentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbGaPWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('participant_set', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('study_consent_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.studyconsentgroup')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dbgapworkspace',
            constraint=models.UniqueConstraint(fields=('study_consent_group', 'phs', 'version'), name='unique_dbgap_workspace'),
        ),
    ]
