# Generated by Django 3.2.16 on 2022-11-30 16:56

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0002_historicaldatausemodifier_historicaldatausepermission_historicalstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('short_name', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
