# Generated by Django 3.2.16 on 2022-12-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0004_remove_duo_models'),
        ('primed_anvil', '0003_studysite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataUseModifier',
        ),
        migrations.DeleteModel(
            name='DataUsePermission',
        ),
        migrations.RemoveField(
            model_name='historicaldatausepermission',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDataUseModifier',
        ),
        migrations.DeleteModel(
            name='HistoricalDataUsePermission',
        ),
    ]
