# Generated by Django 3.2.16 on 2023-01-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0004_remove_duo_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
