# Generated by Django 4.2.13 on 2024-07-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
        ('primed_anvil', '0006_studysite_drupal_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysite',
            name='member_group',
            field=models.ForeignKey(blank=True, help_text='The AnVIL Managed Group associated with this site.', null=True, on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup'),
        ),
    ]
