# Generated by Django 4.2.13 on 2024-07-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
        ('primed_anvil', '0007_studysite_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysite',
            name='member_group',
            field=models.OneToOneField(blank=True, help_text='The AnVIL Managed Group associated with this site.', null=True, on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup'),
        ),
    ]
