version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "django-anvil-consortium-manager"
    allow:
      # Allow only direct dependencies - should be ok with pip-sync?
      - dependency-type: "direct"
    # Allow up to 20 dependencies for pip dependencies
    open-pull-requests-limit: 20
