version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
