version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Allow up to 10 dependencies for pip dependencies
    open-pull-requests-limit: 20

    prod-dependencies-minor-patch:
      dependency-type: "production"
      update-types:
        - "minor"
        - "patch"
    dev-dependencies:
      dependency-type: "development"
