# Generated by Django 3.2.13 on 2022-11-09 23:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('primed_anvil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anvil_consortium_manager', '0003_rename_workspacegroupaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbGaPApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_project_id', models.PositiveIntegerField(help_text='The dbGaP-assigned project_id for this application.', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP project id')),
                ('anvil_group', models.OneToOneField(help_text='The AnVIL managed group that can will access to workspaces under this dbGaP application.', on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL group')),
                ('principal_investigator', models.ForeignKey(help_text='The principal investigator associated with on this dbGaP application.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' dbGaP application',
            },
        ),
        migrations.CreateModel(
            name='dbGaPDataAccessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_dar_data', models.JSONField(null=True)),
                ('dbgap_application', models.ForeignKey(help_text='The dbGaP application associated with this DAR.', on_delete=django.db.models.deletion.PROTECT, to='dbgap.dbgapapplication', verbose_name='dbGaP application')),
            ],
            options={
                'verbose_name': ' dbGaP data access snapshot',
            },
        ),
        migrations.CreateModel(
            name='dbGaPStudyAccession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_phs', models.PositiveIntegerField(help_text='The dbGaP study accession integer associated with this workspace (e.g., 7 for phs000007).', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP phs')),
                ('study', models.ForeignKey(help_text='The study associated with this dbGaP study accession.', on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.study', verbose_name='study')),
            ],
            options={
                'verbose_name': ' dbGaP study accession',
                'verbose_name_plural': ' dbGaP study accessions',
            },
        ),
        migrations.CreateModel(
            name='HistoricaldbGaPWorkspace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('disease_restriction', models.CharField(blank=True, help_text='The disease restriction if required by data_use_permission.', max_length=255, null=True)),
                ('dbgap_version', models.PositiveIntegerField(help_text='The dbGaP study version associated with this Workspace.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP version')),
                ('dbgap_participant_set', models.PositiveIntegerField(help_text='The dbGaP participant set associated with this Workspace.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP participant set')),
                ('dbgap_consent_code', models.PositiveIntegerField(help_text='The numeric code assigned to this consent group by dbGaP', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP consent code')),
                ('dbgap_consent_abbreviation', models.CharField(help_text='The consent abbreviation from dbGaP for this study consent group (e.g., GRU-NPU-MDS).', max_length=63, verbose_name=' dbGaP consent abbreviation')),
                ('data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('acknowledgments', models.TextField(help_text='Acknowledgments associated with data in this workspace.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('data_use_permission', models.ForeignKey(blank=True, db_constraint=False, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.datausepermission')),
                ('dbgap_study_accession', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dbgap.dbgapstudyaccession', verbose_name=' dbGaP study accession')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': 'historical  dbGaP workspace',
                'verbose_name_plural': 'historical  dbGaP workspaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricaldbGaPStudyAccession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_phs', models.PositiveIntegerField(db_index=True, help_text='The dbGaP study accession integer associated with this workspace (e.g., 7 for phs000007).', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP phs')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, db_constraint=False, help_text='The study associated with this dbGaP study accession.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.study', verbose_name='study')),
            ],
            options={
                'verbose_name': 'historical  dbGaP study accession',
                'verbose_name_plural': 'historical  dbGaP study accessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricaldbGaPDataAccessSnapshot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_dar_data', models.JSONField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dbgap_application', models.ForeignKey(blank=True, db_constraint=False, help_text='The dbGaP application associated with this DAR.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dbgap.dbgapapplication', verbose_name='dbGaP application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical  dbGaP data access snapshot',
                'verbose_name_plural': 'historical  dbGaP data access snapshots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricaldbGaPDataAccessRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_dar_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP DAR id')),
                ('dbgap_phs', models.PositiveIntegerField(help_text='The phs number of the study accession that this DAR grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP study accession phs')),
                ('original_version', models.PositiveIntegerField(help_text='The original version of the dbGaP study accession that this application grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP version')),
                ('original_participant_set', models.PositiveIntegerField(help_text='The original participant set of the dbGaP study accession that this application grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP participant set')),
                ('dbgap_consent_code', models.PositiveIntegerField(help_text='The numeric code assigned to this consent group by dbGaP', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP consent code')),
                ('dbgap_consent_abbreviation', models.CharField(help_text='The abbreviation for this consent group.', max_length=31, verbose_name=' dbGaP consent abbreviation')),
                ('dbgap_current_status', models.CharField(choices=[('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('new', 'New')], max_length=31, verbose_name=' dbGaP current status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dbgap_data_access_snapshot', models.ForeignKey(blank=True, db_constraint=False, help_text='The dbGaP data access snapshot from which this record came.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dbgap.dbgapdataaccesssnapshot', verbose_name='dbGaP data access snapshot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical  dbGaP data access request',
                'verbose_name_plural': 'historical  dbGaP data access requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricaldbGaPApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_project_id', models.PositiveIntegerField(db_index=True, help_text='The dbGaP-assigned project_id for this application.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP project id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anvil_group', models.ForeignKey(blank=True, db_constraint=False, help_text='The AnVIL managed group that can will access to workspaces under this dbGaP application.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('principal_investigator', models.ForeignKey(blank=True, db_constraint=False, help_text='The principal investigator associated with on this dbGaP application.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical  dbGaP application',
                'verbose_name_plural': 'historical  dbGaP applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='dbGaPWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('disease_restriction', models.CharField(blank=True, help_text='The disease restriction if required by data_use_permission.', max_length=255, null=True)),
                ('dbgap_version', models.PositiveIntegerField(help_text='The dbGaP study version associated with this Workspace.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP version')),
                ('dbgap_participant_set', models.PositiveIntegerField(help_text='The dbGaP participant set associated with this Workspace.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP participant set')),
                ('dbgap_consent_code', models.PositiveIntegerField(help_text='The numeric code assigned to this consent group by dbGaP', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP consent code')),
                ('dbgap_consent_abbreviation', models.CharField(help_text='The consent abbreviation from dbGaP for this study consent group (e.g., GRU-NPU-MDS).', max_length=63, verbose_name=' dbGaP consent abbreviation')),
                ('data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('acknowledgments', models.TextField(help_text='Acknowledgments associated with data in this workspace.')),
                ('data_use_modifiers', models.ManyToManyField(blank=True, help_text='The DataUseModifiers associated with this study-consent group.', to='primed_anvil.DataUseModifier')),
                ('data_use_permission', models.ForeignKey(help_text='The DataUsePermission associated with this study-consent group.', on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.datausepermission')),
                ('dbgap_study_accession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbgap.dbgapstudyaccession', verbose_name=' dbGaP study accession')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': ' dbGaP workspace',
                'verbose_name_plural': ' dbGaP workspaces',
            },
        ),
        migrations.CreateModel(
            name='dbGaPDataAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_dar_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP DAR id')),
                ('dbgap_phs', models.PositiveIntegerField(help_text='The phs number of the study accession that this DAR grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP study accession phs')),
                ('original_version', models.PositiveIntegerField(help_text='The original version of the dbGaP study accession that this application grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP version')),
                ('original_participant_set', models.PositiveIntegerField(help_text='The original participant set of the dbGaP study accession that this application grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP participant set')),
                ('dbgap_consent_code', models.PositiveIntegerField(help_text='The numeric code assigned to this consent group by dbGaP', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP consent code')),
                ('dbgap_consent_abbreviation', models.CharField(help_text='The abbreviation for this consent group.', max_length=31, verbose_name=' dbGaP consent abbreviation')),
                ('dbgap_current_status', models.CharField(choices=[('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('new', 'New')], max_length=31, verbose_name=' dbGaP current status')),
                ('dbgap_data_access_snapshot', models.ForeignKey(help_text='The dbGaP data access snapshot from which this record came.', on_delete=django.db.models.deletion.CASCADE, to='dbgap.dbgapdataaccesssnapshot', verbose_name='dbGaP data access snapshot')),
            ],
            options={
                'verbose_name': ' dbGaP data access request',
            },
        ),
        migrations.AddConstraint(
            model_name='dbgapworkspace',
            constraint=models.UniqueConstraint(fields=('dbgap_study_accession', 'dbgap_version', 'dbgap_consent_abbreviation'), name='unique_dbgap_workspace'),
        ),
        migrations.AddConstraint(
            model_name='dbgapdataaccessrequest',
            constraint=models.UniqueConstraint(fields=('dbgap_data_access_snapshot', 'dbgap_phs', 'dbgap_consent_code'), name='unique_dbgap_data_access_request'),
        ),
        migrations.AddConstraint(
            model_name='dbgapdataaccessrequest',
            constraint=models.UniqueConstraint(fields=('dbgap_data_access_snapshot', 'dbgap_dar_id'), name='unique_dbgap_data_access_dar_id'),
        ),
    ]
