# Generated by Django 3.2.13 on 2022-11-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0001_initial'),
        ('dbgap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldbgapstudyaccession',
            name='study',
        ),
        migrations.RemoveField(
            model_name='dbgapstudyaccession',
            name='study',
        ),
        migrations.AddField(
            model_name='dbgapstudyaccession',
            name='study',
            field=models.ManyToManyField(help_text='The studies associated with this dbGaP study accession.', to='primed_anvil.Study', verbose_name='study'),
        ),
    ]
