# Generated by Django 3.2.13 on 2022-09-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0002_alter_dbgapstudy_phs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dbgapworkspace',
            name='unique_dbgap_workspace',
        ),
        migrations.AddConstraint(
            model_name='dbgapworkspace',
            constraint=models.UniqueConstraint(fields=('dbgap_study', 'dbgap_version', 'full_consent_code'), name='unique_dbgap_workspace'),
        ),
    ]
