# Generated by Django 3.2.13 on 2022-11-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0001_initial'),
        ('dbgap', '0002_auto_20221114_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbgapstudyaccession',
            name='study',
        ),
        migrations.AddField(
            model_name='dbgapstudyaccession',
            name='studies',
            field=models.ManyToManyField(help_text='The studies associated with this dbGaP study accession.', to='primed_anvil.Study'),
        ),
    ]
