# Generated by Django 3.2.16 on 2022-12-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0003_requestedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbgapworkspace',
            name='data_use_modifiers',
        ),
        migrations.RemoveField(
            model_name='dbgapworkspace',
            name='data_use_permission',
        ),
        migrations.RemoveField(
            model_name='dbgapworkspace',
            name='disease_restriction',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapworkspace',
            name='data_use_permission',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapworkspace',
            name='disease_restriction',
        ),
    ]
