# Generated by Django 3.2.13 on 2022-09-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0003_auto_20220929_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbgapstudy',
            options={'verbose_name': ' dbGaP study', 'verbose_name_plural': ' dbGaP studies'},
        ),
    ]
