# Generated by Django 3.2.16 on 2022-12-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0001_initial'),
        ('dbgap', '0004_remove_duo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapworkspace',
            name='data_use_modifiers',
            field=models.ManyToManyField(blank=True, help_text='The DataUseModifiers associated with this study-consent group.', to='duo.DataUseModifier', verbose_name='DUO data use modifiers'),
        ),
        migrations.AddField(
            model_name='dbgapworkspace',
            name='data_use_permission',
            field=models.ForeignKey(blank=True, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.PROTECT, to='duo.datausepermission', verbose_name='DUO data use permission'),
        ),
        migrations.AddField(
            model_name='dbgapworkspace',
            name='disease_term',
            field=models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term'),
        ),
        migrations.AddField(
            model_name='historicaldbgapworkspace',
            name='data_use_permission',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='duo.datausepermission', verbose_name='DUO data use permission'),
        ),
        migrations.AddField(
            model_name='historicaldbgapworkspace',
            name='disease_term',
            field=models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term'),
        ),
    ]
