# Generated by Django 3.2.13 on 2022-09-30 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0005_auto_20220929_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgapstudy',
            name='phs',
            field=models.PositiveIntegerField(help_text='The dbGaP study accession integer associated with this workspace (e.g., 7 for phs000007).', unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
