# Generated by Django 3.2.16 on 2023-01-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0005_availabledata'),
        ('dbgap', '0005_add_duo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapworkspace',
            name='available_data',
            field=models.ManyToManyField(blank=True, help_text='Data available in this accession.', to='primed_anvil.AvailableData'),
        ),
    ]
