# Generated by Django 3.2.16 on 2022-12-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0005_add_duo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbgapworkspace',
            name='disease_restriction',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapworkspace',
            name='disease_restriction',
        ),
        migrations.AddField(
            model_name='dbgapworkspace',
            name='disease_term',
            field=models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term'),
        ),
        migrations.AddField(
            model_name='historicaldbgapworkspace',
            name='disease_term',
            field=models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term'),
        ),
    ]
