# Generated by Django 3.2.13 on 2022-09-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0001_initial'),
        ('dbgap', '0006_alter_dbgapstudy_phs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dbGaPStudy',
            new_name='dbGaPStudyAccession',
        ),
        migrations.AlterModelOptions(
            name='dbgapstudyaccession',
            options={'verbose_name': ' dbGaP study accession', 'verbose_name_plural': ' dbGaP study accessions'},
        ),
        migrations.RemoveConstraint(
            model_name='dbgapworkspace',
            name='unique_dbgap_workspace',
        ),
        migrations.RenameField(
            model_name='dbgapworkspace',
            old_name='dbgap_study',
            new_name='dbgap_study_accession',
        ),
        migrations.AddConstraint(
            model_name='dbgapworkspace',
            constraint=models.UniqueConstraint(fields=('dbgap_study_accession', 'dbgap_version', 'full_consent_code'), name='unique_dbgap_workspace'),
        ),
    ]
