# Generated by Django 3.2.13 on 2022-09-30 22:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbgap', '0007_rename_dbgapstudyaccession'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbGaPApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('project_id', models.PositiveIntegerField(help_text='The dbGaP-assigned project_id for this application.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('principal_investigator', models.ForeignKey(help_text='The principal investigator associated with on this dbGaP application.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' dbGaP application',
            },
        ),
    ]
