# Generated by Django 4.2.8 on 2024-01-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbgap", "0009_dbgapworkspace_is_sensitive_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbgapworkspace",
            old_name="is_sensitive",
            new_name="gsr_restricted",
        ),
        migrations.RenameField(
            model_name="historicaldbgapworkspace",
            old_name="is_sensitive",
            new_name="gsr_restricted",
        ),
    ]
