# Generated by Django 3.2.13 on 2022-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0009_dbgapdataaccessrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dbgapworkspace',
            name='unique_dbgap_workspace',
        ),
        migrations.RenameField(
            model_name='dbgapworkspace',
            old_name='full_consent_code',
            new_name='dbgap_consent_abbreviation',
        ),
        migrations.AddConstraint(
            model_name='dbgapworkspace',
            constraint=models.UniqueConstraint(fields=('dbgap_study_accession', 'dbgap_version', 'dbgap_consent_abbreviation'), name='unique_dbgap_workspace'),
        ),
    ]
