# Generated by Django 3.2.13 on 2022-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0010_auto_20221003_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgapworkspace',
            name='dbgap_consent_abbreviation',
            field=models.CharField(help_text='The consent abbreviation from dbGaP for this study consent group (e.g., GRU-NPU-MDS).', max_length=63),
        ),
    ]
