# Generated by Django 4.2.11 on 2024-04-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbgap", "0011_gsr_restricted_help_and_verbose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbgapworkspace",
            name="disease_term",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The disease term if required by data_use_permission.",
                max_length=255,
                verbose_name="DUO disease term",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldbgapworkspace",
            name="disease_term",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The disease term if required by data_use_permission.",
                max_length=255,
                verbose_name="DUO disease term",
            ),
        ),
    ]
