# Generated by Django 3.2.13 on 2022-10-03 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0011_alter_dbgapworkspace_dbgap_consent_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapworkspace',
            name='dbgap_consent_code',
            field=models.PositiveIntegerField(default=None, help_text='The numeric code assigned to this consent group by dbGaP', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
