# Generated by Django 3.2.13 on 2022-10-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0012_dbgapworkspace_dbgap_consent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_current_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('closed', 'Closed')], default='approved', max_length=31),
            preserve_default=False,
        ),
    ]
