# Generated by Django 4.2.13 on 2024-06-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbgap', '0012_alter_dbgapworkspace_disease_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapapplication',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='The internal collaborators or trainees covered under this dbGaP application.', related_name='collaborator_dbgap_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dbgapapplication',
            name='principal_investigator',
            field=models.ForeignKey(help_text='The principal investigator associated with on this dbGaP application.', on_delete=django.db.models.deletion.PROTECT, related_name='pi_dbgap_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
