# Generated by Django 3.2.13 on 2022-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0013_dbgapdataaccessrequest_dbgap_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_current_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('new', 'New')], max_length=31),
        ),
    ]
