# Generated by Django 3.2.13 on 2022-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0015_simplehistory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dbgapdataaccessrequest',
            constraint=models.UniqueConstraint(fields=('dbgap_application', 'dbgap_study_accession', 'dbgap_consent_code'), name='unique_dbgap_data_access_request'),
        ),
    ]
