# Generated by Django 3.2.13 on 2022-10-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0002_account_verification'),
        ('dbgap', '0017_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapapplication',
            name='anvil_group',
            field=models.OneToOneField(default=None, help_text='The AnVIL managed group that can will access to workspaces under this dbGaP application.', on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldbgapapplication',
            name='anvil_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The AnVIL managed group that can will access to workspaces under this dbGaP application.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL group'),
        ),
    ]
