# Generated by Django 3.2.13 on 2022-10-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0018_auto_20221012_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapapplication',
            name='dbgap_dar_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldbgapapplication',
            name='dbgap_dar_data',
            field=models.JSONField(null=True),
        ),
    ]
