# Generated by Django 3.2.13 on 2022-10-18 23:15

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0019_dbgapapplication_add_dbgap_dar_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbgapapplication',
            name='dbgap_dar_data',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapapplication',
            name='dbgap_dar_data',
        ),
        migrations.CreateModel(
            name='dbGaPDataAccessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dbgap_dar_data', models.JSONField(null=True)),
                ('dbgap_application', models.ForeignKey(help_text='The dbGaP application associated with this DAR.', on_delete=django.db.models.deletion.PROTECT, to='dbgap.dbgapapplication', verbose_name='dbGaP application')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
