# Generated by Django 3.2.13 on 2022-10-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0021_auto_20221018_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldbgapdataaccesssnapshot',
            name='dbgap_application',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapdataaccesssnapshot',
            name='history_user',
        ),
        migrations.RemoveConstraint(
            model_name='dbgapdataaccessrequest',
            name='unique_dbgap_data_access_request',
        ),
        migrations.RemoveField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_application',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapdataaccessrequest',
            name='dbgap_application',
        ),
        migrations.AddField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_data_access_snapshot',
            field=models.ForeignKey(default=None, help_text='The dbGaP data access snapshot from which this record came.', on_delete=django.db.models.deletion.PROTECT, to='dbgap.dbgapdataaccesssnapshot', verbose_name='dbGaP data access snapshot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldbgapdataaccessrequest',
            name='dbgap_data_access_snapshot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The dbGaP data access snapshot from which this record came.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dbgap.dbgapdataaccesssnapshot', verbose_name='dbGaP data access snapshot'),
        ),
        migrations.AddConstraint(
            model_name='dbgapdataaccessrequest',
            constraint=models.UniqueConstraint(fields=('dbgap_data_access_snapshot', 'dbgap_study_accession', 'dbgap_consent_code'), name='unique_dbgap_data_access_request'),
        ),
        migrations.AddConstraint(
            model_name='dbgapdataaccessrequest',
            constraint=models.UniqueConstraint(fields=('dbgap_data_access_snapshot', 'dbgap_dar_id'), name='unique_dbgap_data_access_dar_id'),
        ),
        migrations.DeleteModel(
            name='HistoricaldbGaPDataAccessSnapshot',
        ),
    ]
