# Generated by Django 3.2.13 on 2022-10-19 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0022_auto_20221019_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_dar_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP DAR id'),
        ),
        migrations.AlterField(
            model_name='historicaldbgapdataaccessrequest',
            name='dbgap_dar_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP DAR id'),
        ),
    ]
