# Generated by Django 3.2.13 on 2022-10-20 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0023_auto_20221019_1505'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dbgapdataaccessrequest',
            name='unique_dbgap_data_access_request',
        ),
        migrations.RemoveField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_study_accession',
        ),
        migrations.RemoveField(
            model_name='historicaldbgapdataaccessrequest',
            name='dbgap_study_accession',
        ),
        migrations.AddField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_phs',
            field=models.PositiveIntegerField(default=None, help_text='The phs number of the study accession that this DAR grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP study accession phs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldbgapdataaccessrequest',
            name='dbgap_phs',
            field=models.PositiveIntegerField(default=None, help_text='The phs number of the study accession that this DAR grants access to.', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP study accession phs'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dbgapdataaccessrequest',
            constraint=models.UniqueConstraint(fields=('dbgap_data_access_snapshot', 'dbgap_phs', 'dbgap_consent_code'), name='unique_dbgap_data_access_request'),
        ),
    ]
