# Generated by Django 3.2.13 on 2022-10-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0024_dbgapdataaccessrequest_phs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbgapdataaccessrequest',
            old_name='dbgap_participant_set',
            new_name='original_participant_set',
        ),
        migrations.RenameField(
            model_name='dbgapdataaccessrequest',
            old_name='dbgap_version',
            new_name='original_version',
        ),
        migrations.RenameField(
            model_name='historicaldbgapdataaccessrequest',
            old_name='dbgap_participant_set',
            new_name='original_participant_set',
        ),
        migrations.RenameField(
            model_name='historicaldbgapdataaccessrequest',
            old_name='dbgap_version',
            new_name='original_version',
        ),
    ]
