# Generated by Django 3.2.13 on 2022-10-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0025_auto_20221021_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgapdataaccessrequest',
            name='dbgap_data_access_snapshot',
            field=models.ForeignKey(help_text='The dbGaP data access snapshot from which this record came.', on_delete=django.db.models.deletion.CASCADE, to='dbgap.dbgapdataaccesssnapshot', verbose_name='dbGaP data access snapshot'),
        ),
    ]
