# Generated by Django 3.2.13 on 2022-10-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0026_dbgapdataaccessrequest_dbgap_data_access_snapshot_cascade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbgapapplication',
            old_name='project_id',
            new_name='dbgap_project_id',
        ),
        migrations.RenameField(
            model_name='historicaldbgapapplication',
            old_name='project_id',
            new_name='dbgap_project_id',
        ),
    ]
