# Generated by Django 3.2.13 on 2022-10-24 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0029_auto_20221024_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgapstudyaccession',
            name='dbgap_phs',
            field=models.PositiveIntegerField(help_text='The dbGaP study accession integer associated with this workspace (e.g., 7 for phs000007).', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP phs'),
        ),
        migrations.AlterField(
            model_name='historicaldbgapstudyaccession',
            name='dbgap_phs',
            field=models.PositiveIntegerField(db_index=True, help_text='The dbGaP study accession integer associated with this workspace (e.g., 7 for phs000007).', validators=[django.core.validators.MinValueValidator(1)], verbose_name=' dbGaP phs'),
        ),
    ]
