# Generated by Django 3.2.13 on 2022-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgap', '0030_auto_20221024_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgapworkspace',
            name='acknowledgments',
            field=models.TextField(default='foo', help_text='Acknowledgments associated with data in this workspace.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldbgapworkspace',
            name='acknowledgments',
            field=models.TextField(default='foo', help_text='Acknowledgments associated with data in this workspace.'),
            preserve_default=False,
        ),
    ]
