# Generated by Django 3.2.16 on 2023-05-08 20:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duo', '0001_initial'),
        ('anvil_consortium_manager', '0008_workspace_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primed_anvil', '0005_availabledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('major_version', models.IntegerField(help_text='Major version of the CDSA. Changes to the major version require resigning.', validators=[django.core.validators.MinValueValidator(1)])),
                ('minor_version', models.IntegerField(help_text='Minor version of the CDSA. Changes to the minor version do not require resigning.', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_approved', models.DateField(default=datetime.date.today, help_text='Date that this AgreementVersion was approved by the PRIMED Consortium.')),
            ],
            options={
                'ordering': ['major_version', 'minor_version'],
            },
        ),
        migrations.CreateModel(
            name='SignedAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cc_id', models.IntegerField(help_text='Identifier assigned by the Coordinating Center.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('representative_role', models.CharField(help_text="Representative's role in the group.", max_length=255)),
                ('signing_institution', models.CharField(help_text='Signing institution for this Agreement.', max_length=255)),
                ('type', models.CharField(choices=[('member', 'Member'), ('data_affiliate', 'Data affiliate'), ('non_data_affiliate', 'Non-data affiliate')], max_length=31, verbose_name='Agreement type')),
                ('is_primary', models.BooleanField(help_text='Indicator of whether this is a primary Agreement (and not a component Agreement).')),
                ('date_signed', models.DateField(default=datetime.date.today, help_text='Date that this Agreement signed by the institution.')),
                ('anvil_access_group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL access group')),
                ('representative', models.ForeignKey(help_text='The investigator who signed this Agreement.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(help_text='The version of the Agreement that was signed.', on_delete=django.db.models.deletion.PROTECT, to='cdsa.agreementversion')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataAffiliateAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('signed_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cdsa.signedagreement')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('signed_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cdsa.signedagreement')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonDataAffiliateAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('signed_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cdsa.signedagreement')),
                ('affiliation', models.CharField(help_text='The affiliation of the person signing this CDSA.', max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSignedAgreement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cc_id', models.IntegerField(db_index=True, help_text='Identifier assigned by the Coordinating Center.', validators=[django.core.validators.MinValueValidator(1)])),
                ('representative_role', models.CharField(help_text="Representative's role in the group.", max_length=255)),
                ('signing_institution', models.CharField(help_text='Signing institution for this Agreement.', max_length=255)),
                ('type', models.CharField(choices=[('member', 'Member'), ('data_affiliate', 'Data affiliate'), ('non_data_affiliate', 'Non-data affiliate')], max_length=31, verbose_name='Agreement type')),
                ('is_primary', models.BooleanField(help_text='Indicator of whether this is a primary Agreement (and not a component Agreement).')),
                ('date_signed', models.DateField(default=datetime.date.today, help_text='Date that this Agreement signed by the institution.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anvil_access_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL access group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(blank=True, db_constraint=False, help_text='The investigator who signed this Agreement.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, db_constraint=False, help_text='The version of the Agreement that was signed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cdsa.agreementversion')),
            ],
            options={
                'verbose_name': 'historical signed agreement',
                'verbose_name_plural': 'historical signed agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNonDataAffiliateAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('affiliation', models.CharField(help_text='The affiliation of the person signing this CDSA.', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cdsa.signedagreement')),
            ],
            options={
                'verbose_name': 'historical non data affiliate agreement',
                'verbose_name_plural': 'historical non data affiliate agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMemberAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cdsa.signedagreement')),
                ('study_site', models.ForeignKey(blank=True, db_constraint=False, help_text='Study Site that this agreement is associated with.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.studysite')),
            ],
            options={
                'verbose_name': 'historical member agreement',
                'verbose_name_plural': 'historical member agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataAffiliateAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anvil_upload_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cdsa.signedagreement')),
                ('study', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.study')),
            ],
            options={
                'verbose_name': 'historical data affiliate agreement',
                'verbose_name_plural': 'historical data affiliate agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCDSAWorkspace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('disease_term', models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term')),
                ('data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('acknowledgments', models.TextField(help_text='Acknowledgments associated with data in this workspace.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('data_use_permission', models.ForeignKey(blank=True, db_constraint=False, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='duo.datausepermission', verbose_name='DUO data use permission')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who requested creation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, db_constraint=False, help_text='The study associated with data in this workspace.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.study')),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': 'historical  CDSA workspace',
                'verbose_name_plural': 'historical  CDSA workspaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAgreementVersion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('major_version', models.IntegerField(help_text='Major version of the CDSA. Changes to the major version require resigning.', validators=[django.core.validators.MinValueValidator(1)])),
                ('minor_version', models.IntegerField(help_text='Minor version of the CDSA. Changes to the minor version do not require resigning.', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_approved', models.DateField(default=datetime.date.today, help_text='Date that this AgreementVersion was approved by the PRIMED Consortium.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical agreement version',
                'verbose_name_plural': 'historical agreement versions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CDSAWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('disease_term', models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term')),
                ('data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('acknowledgments', models.TextField(help_text='Acknowledgments associated with data in this workspace.')),
                ('available_data', models.ManyToManyField(blank=True, help_text='Data available in this accession.', to='primed_anvil.AvailableData')),
                ('data_use_modifiers', models.ManyToManyField(blank=True, help_text='The DataUseModifiers associated with this study-consent group.', to='duo.DataUseModifier', verbose_name='DUO data use modifiers')),
                ('data_use_permission', models.ForeignKey(blank=True, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.PROTECT, to='duo.datausepermission', verbose_name='DUO data use permission')),
                ('requested_by', models.ForeignKey(help_text='The user who requested creation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(help_text='The study associated with data in this workspace.', on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.study')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': ' CDSA workspace',
                'verbose_name_plural': ' CDSA workspaces',
            },
        ),
        migrations.AddConstraint(
            model_name='agreementversion',
            constraint=models.UniqueConstraint(fields=('major_version', 'minor_version'), name='unique_agreement_version'),
        ),
        migrations.AddField(
            model_name='memberagreement',
            name='study_site',
            field=models.ForeignKey(help_text='Study Site that this agreement is associated with.', on_delete=django.db.models.deletion.CASCADE, to='primed_anvil.studysite'),
        ),
        migrations.AddField(
            model_name='dataaffiliateagreement',
            name='anvil_upload_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup'),
        ),
        migrations.AddField(
            model_name='dataaffiliateagreement',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.study'),
        ),
    ]
