# Generated by Django 3.2.16 on 2023-04-20 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0008_workspace_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cc_id', models.IntegerField(help_text='Identifier assigned by the Coordinating Center.', unique=True)),
                ('representative_role', models.CharField(help_text="Representative's role in the group.", max_length=255)),
                ('signing_institution', models.CharField(help_text='Signing institution for this Agreement.', max_length=255)),
                ('type', models.CharField(choices=[('member', 'Member'), ('data_affiliate', 'Data affiliate'), ('non_data_affiliate', 'Non-data affiliate')], max_length=31, verbose_name='Agreement type')),
                ('is_primary', models.BooleanField(help_text='Indicator of whether this is a primary Agreement (and not a component Agreement).')),
                ('date_signed', models.DateField(default=datetime.date.today, help_text='Date that this Agreement signed by the institution.')),
                ('anvil_access_group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL access group')),
                ('representative', models.ForeignKey(help_text='The investigator who signed this Agreement.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(help_text='The version of the Agreement that was signed.', on_delete=django.db.models.deletion.PROTECT, to='cdsa.agreementversion')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSignedAgreement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cc_id', models.IntegerField(db_index=True, help_text='Identifier assigned by the Coordinating Center.')),
                ('representative_role', models.CharField(help_text="Representative's role in the group.", max_length=255)),
                ('signing_institution', models.CharField(help_text='Signing institution for this Agreement.', max_length=255)),
                ('type', models.CharField(choices=[('member', 'Member'), ('data_affiliate', 'Data affiliate'), ('non_data_affiliate', 'Non-data affiliate')], max_length=31, verbose_name='Agreement type')),
                ('is_primary', models.BooleanField(help_text='Indicator of whether this is a primary Agreement (and not a component Agreement).')),
                ('date_signed', models.DateField(default=datetime.date.today, help_text='Date that this Agreement signed by the institution.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anvil_access_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.managedgroup', verbose_name=' AnVIL access group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(blank=True, db_constraint=False, help_text='The investigator who signed this Agreement.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, db_constraint=False, help_text='The version of the Agreement that was signed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cdsa.agreementversion')),
            ],
            options={
                'verbose_name': 'historical signed agreement',
                'verbose_name_plural': 'historical signed agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
