# Generated by Django 3.2.16 on 2023-03-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdsa',
            old_name='instutition',
            new_name='institution',
        ),
    ]
