# Generated by Django 3.2.16 on 2023-04-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('primed_anvil', '0005_availabledata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdsa', '0002_historicalsignedagreement_signedagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('signed_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cdsa.signedagreement')),
                ('study_site', models.ForeignKey(help_text='Study Site that this agreement is associated with.', on_delete=django.db.models.deletion.CASCADE, to='primed_anvil.studysite')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalMemberAgreement',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cdsa.signedagreement')),
                ('study_site', models.ForeignKey(blank=True, db_constraint=False, help_text='Study Site that this agreement is associated with.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.studysite')),
            ],
            options={
                'verbose_name': 'historical member agreement',
                'verbose_name_plural': 'historical member agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
