# Generated by Django 3.2.16 on 2023-03-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0002_rename_instutition_cdsa_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdsa',
            old_name='representatitive_role',
            new_name='representative_role',
        ),
    ]
