# Generated by Django 3.2.16 on 2023-05-02 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0005_historicalnondataaffiliateagreement_nondataaffiliateagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsignedagreement',
            name='cc_id',
            field=models.IntegerField(db_index=True, help_text='Identifier assigned by the Coordinating Center.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='signedagreement',
            name='cc_id',
            field=models.IntegerField(help_text='Identifier assigned by the Coordinating Center.', unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
