# Generated by Django 3.2.19 on 2023-08-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0005_agreementversion_remove_field_major_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementversion',
            options={'ordering': ['major_version', 'minor_version']},
        ),
        migrations.RenameField(
            model_name='agreementversion',
            old_name='major_version_fk',
            new_name='major_version',
        ),
        migrations.RenameField(
            model_name='historicalagreementversion',
            old_name='major_version_fk',
            new_name='major_version',
        ),
        migrations.AddConstraint(
            model_name='agreementversion',
            constraint=models.UniqueConstraint(fields=('major_version', 'minor_version'), name='unique_agreement_version_2'),
        ),
    ]
