# Generated by Django 3.2.19 on 2023-08-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0006_agreementversion_rename_major_version_fk_to_major_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementversion',
            name='major_version',
            field=models.ForeignKey(default=None, help_text='Major version of the CDSA. Changes to the major version require resigning.', on_delete=django.db.models.deletion.CASCADE, to='cdsa.agreementmajorversion'),
            preserve_default=False,
        ),
    ]
