# Generated by Django 3.2.16 on 2023-05-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0008_workspace_is_locked'),
        ('primed_anvil', '0005_availabledata'),
        ('duo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdsa', '0006_auto_20230502_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCDSAWorkspace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('disease_term', models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term')),
                ('data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('acknowledgments', models.TextField(help_text='Acknowledgments associated with data in this workspace.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('data_use_permission', models.ForeignKey(blank=True, db_constraint=False, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='duo.datausepermission', verbose_name='DUO data use permission')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who requested creation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, db_constraint=False, help_text='The study associated with data in this workspace.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primed_anvil.study')),
                ('workspace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': 'historical  CDSA workspace',
                'verbose_name_plural': 'historical  CDSA workspaces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CDSAWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('disease_term', models.CharField(blank=True, help_text='The disease term if required by data_use_permission.', max_length=255, null=True, verbose_name='DUO disease term')),
                ('data_use_limitations', models.TextField(help_text='The full data use limitations for this workspace.')),
                ('acknowledgments', models.TextField(help_text='Acknowledgments associated with data in this workspace.')),
                ('available_data', models.ManyToManyField(blank=True, help_text='Data available in this accession.', to='primed_anvil.AvailableData')),
                ('data_use_modifiers', models.ManyToManyField(blank=True, help_text='The DataUseModifiers associated with this study-consent group.', to='duo.DataUseModifier', verbose_name='DUO data use modifiers')),
                ('data_use_permission', models.ForeignKey(blank=True, help_text='The DataUsePermission associated with this study-consent group.', null=True, on_delete=django.db.models.deletion.PROTECT, to='duo.datausepermission', verbose_name='DUO data use permission')),
                ('requested_by', models.ForeignKey(help_text='The user who requested creation.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(help_text='The study associated with data in this workspace.', on_delete=django.db.models.deletion.PROTECT, to='primed_anvil.study')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
            options={
                'verbose_name': ' CDSA workspace',
                'verbose_name_plural': ' CDSA workspaces',
            },
        ),
    ]
