# Generated by Django 3.2.19 on 2023-09-13 22:48

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0007_alter_agreementversion_major_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementmajorversion',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='valid', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='agreementmajorversion',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='historicalagreementmajorversion',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='valid', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='historicalagreementmajorversion',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
