# Generated by Django 3.2.19 on 2023-09-19 17:33

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cdsa', '0008_agreementmajorversion_add_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignedagreement',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='active', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='historicalsignedagreement',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='signedagreement',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='active', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='signedagreement',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='agreementmajorversion',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Boolean indicator of whether this version is valid.'),
        ),
        migrations.AlterField(
            model_name='historicalagreementmajorversion',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Boolean indicator of whether this version is valid.'),
        ),
    ]
