# Generated by Django 4.2.7 on 2023-12-04 23:27

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0009_signedagreement_add_field_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsignedagreement",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("active", "Active"),
                    ("withdrawn", "Withdrawn"),
                    ("lapsed", "Lapsed"),
                ],
                default="active",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="signedagreement",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("active", "Active"),
                    ("withdrawn", "Withdrawn"),
                    ("lapsed", "Lapsed"),
                ],
                default="active",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
