# Generated by Django 4.2.8 on 2024-01-18 23:49

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0010_alter_historicalsignedagreement_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsignedagreement",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("active", "Active"),
                    ("withdrawn", "Withdrawn"),
                    ("lapsed", "Lapsed"),
                    ("replaced", "Replaced"),
                ],
                default="active",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="signedagreement",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("active", "Active"),
                    ("withdrawn", "Withdrawn"),
                    ("lapsed", "Lapsed"),
                    ("replaced", "Replaced"),
                ],
                default="active",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
