# Generated by Django 4.2.8 on 2024-01-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0012_cdsaworkspace_is_sensitive_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cdsaworkspace",
            old_name="is_sensitive",
            new_name="gsr_restricted",
        ),
        migrations.RenameField(
            model_name="historicalcdsaworkspace",
            old_name="is_sensitive",
            new_name="gsr_restricted",
        ),
    ]
