# Generated by Django 4.2.8 on 2024-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0013_rename_is_sensitive_cdsaworkspace_gsr_sensitive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdsaworkspace",
            name="gsr_restricted",
            field=models.BooleanField(
                help_text="Indicator of whether public posting of GSRs is restricted.",
                verbose_name="GSR restricted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcdsaworkspace",
            name="gsr_restricted",
            field=models.BooleanField(
                help_text="Indicator of whether public posting of GSRs is restricted.",
                verbose_name="GSR restricted?",
            ),
        ),
    ]
