# Generated by Django 4.2.10 on 2024-03-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0015_dataaffiliateagreement_additional_limitations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdsaworkspace",
            name="data_use_limitations",
        ),
        migrations.RemoveField(
            model_name="historicalcdsaworkspace",
            name="data_use_limitations",
        ),
        migrations.AddField(
            model_name="cdsaworkspace",
            name="additional_limitations",
            field=models.TextField(
                blank=True,
                help_text="Additional data use limitations that cannot be captured by DUO.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcdsaworkspace",
            name="additional_limitations",
            field=models.TextField(
                blank=True,
                help_text="Additional data use limitations that cannot be captured by DUO.",
            ),
        ),
    ]
