# Generated by Django 4.2.10 on 2024-03-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0015_dataaffiliateagreement_additional_limitations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cdsaworkspace",
            old_name="data_use_limitations",
            new_name="additional_limitations",
        ),
        migrations.RenameField(
            model_name="historicalcdsaworkspace",
            old_name="data_use_limitations",
            new_name="additional_limitations",
        ),
    ]
