# Generated by Django 4.2.10 on 2024-03-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cdsa",
            "0016_rename_data_use_limitations_cdsaworkspace_additional_limitations_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdsaworkspace",
            name="additional_limitations",
            field=models.TextField(
                blank=True,
                help_text="Additional data use limitations that cannot be captured by DUO.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcdsaworkspace",
            name="additional_limitations",
            field=models.TextField(
                blank=True,
                help_text="Additional data use limitations that cannot be captured by DUO.",
            ),
        ),
    ]
