# Generated by Django 4.2.10 on 2024-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0019_alter_signedagreement_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataaffiliateagreement",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicator of whether this is a primary Agreement (and not a component Agreement).",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldataaffiliateagreement",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicator of whether this is a primary Agreement (and not a component Agreement).",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmemberagreement",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicator of whether this is a primary Agreement (and not a component Agreement).",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberagreement",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicator of whether this is a primary Agreement (and not a component Agreement).",
            ),
            preserve_default=False,
        ),
    ]
