# Generated by Django 4.2.10 on 2024-03-15 22:44

from django.db import migrations

def forward_populate_memberagreement_is_primary(apps, schema_editor):
    """Populate the MemberAgreement is_primary field using is_primary from the associated SignedAgreement."""
    MemberAgreement = apps.get_model("cdsa", "MemberAgreement")
    for row in MemberAgreement.objects.all():
        row.is_primary = row.signed_agreement.is_primary
        row.save(update_fields=["is_primary"])


def forward_populate_dataaffiliateagreement_is_primary(apps, schema_editor):
    """Populate the DataAffiliateAgreement is_primary field using is_primary from the associated SignedAgreement."""
    DataAffiliateAgreement = apps.get_model("cdsa", "DataAffiliateAgreement")
    for row in DataAffiliateAgreement.objects.all():
        row.is_primary = row.signed_agreement.is_primary
        row.save(update_fields=["is_primary"])

def backward_populate_memberagreement_is_primary(apps, schema_editor):
    """Populate the MemberAgreement is_primary field using is_primary from the associated SignedAgreement."""
    MemberAgreement = apps.get_model("cdsa", "MemberAgreement")
    for row in MemberAgreement.objects.all():
        row.signed_agreement.is_primary = row.is_primary
        row.signed_agreement.save(update_fields=["is_primary"])

def backward_populate_dataaffiliateagreement_is_primary(apps, schema_editor):
    """Populate the DataAffiliateAgreement is_primary field using is_primary from the associated SignedAgreement."""
    DataAffiliateAgreement = apps.get_model("cdsa", "DataAffiliateAgreement")
    for row in DataAffiliateAgreement.objects.all():
        row.signed_agreement.is_primary = row.is_primary
        row.signed_agreement.save(update_fields=["is_primary"])

def backward_populate_nondataaffiliateagreement_is_primary(apps, schema_editor):
    """Set the NonDataAffiliateAgreement.signed_agreement.is_primary field to True."""
    NonDataAffiliateAgreement = apps.get_model("cdsa", "NonDataAffiliateAgreement")
    for row in NonDataAffiliateAgreement.objects.all():
        row.signed_agreement.is_primary = True
        row.signed_agreement.save(update_fields=["is_primary"])

class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0020_dataaffiliateagreement_is_primary_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forward_populate_memberagreement_is_primary,
            reverse_code=backward_populate_memberagreement_is_primary,
        ),
        migrations.RunPython(
            forward_populate_dataaffiliateagreement_is_primary,
            reverse_code=backward_populate_dataaffiliateagreement_is_primary,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=backward_populate_nondataaffiliateagreement_is_primary,
        ),
    ]
