# Generated by Django 4.2.11 on 2024-04-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdsa", "0022_remove_signedagreement_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdsaworkspace",
            name="disease_term",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The disease term if required by data_use_permission.",
                max_length=255,
                verbose_name="DUO disease term",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcdsaworkspace",
            name="disease_term",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The disease term if required by data_use_permission.",
                max_length=255,
                verbose_name="DUO disease term",
            ),
        ),
    ]
