# Generated by Django 4.2.13 on 2024-06-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdsa', '0023_alter_cdsaworkspace_disease_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaffiliateagreement',
            name='uploaders',
            field=models.ManyToManyField(blank=True, help_text='Investigators who have permission to upload data under this Agreement.', related_name='uploader_signed_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedagreement',
            name='accessors',
            field=models.ManyToManyField(blank=True, help_text='Investigators who have access to data under this Agreement.', related_name='accessor_signed_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signedagreement',
            name='representative',
            field=models.ForeignKey(help_text='The investigator who signed this Agreement.', on_delete=django.db.models.deletion.PROTECT, related_name='representative_signed_agreements', to=settings.AUTH_USER_MODEL),
        ),
    ]
