# Generated by Django 3.2.16 on 2023-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous_workspaces', '0006_historicalopenaccessworkspace_openaccessworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopenaccessworkspace',
            name='data_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='data URL'),
        ),
        migrations.AddField(
            model_name='openaccessworkspace',
            name='data_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='data URL'),
        ),
    ]
