# Generated by Django 3.2.19 on 2023-11-13 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0015_add_new_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscellaneous_workspaces', '0008_dataprepworkspace_historicaldataprepworkspace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalExampleWorkspace',
            new_name='HistoricalResourceWorkspace',
        ),
        migrations.RenameModel(
            old_name='ExampleWorkspace',
            new_name='ResourceWorkspace',
        ),
        migrations.AlterModelOptions(
            name='historicalresourceworkspace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resource workspace', 'verbose_name_plural': 'historical resource workspaces'},
        ),
        migrations.AlterField(
            model_name='dataprepworkspace',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicator of whether this workspace is currently being used to prepare data.'),
        ),
        migrations.AlterField(
            model_name='historicaldataprepworkspace',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicator of whether this workspace is currently being used to prepare data.'),
        ),
    ]
