# Generated by Django 3.2.19 on 2023-11-13 20:12

from django.db import migrations


def workspace_type_example_to_resource(apps, schema_editor):
    """Change the workspace type from "example" to "resource"."""
    Workspace = apps.get_model("anvil_consortium_manager", "Workspace")

    for row in Workspace.objects.filter(workspace_type="example"):
        row.workspace_type = "resource"
        row.save(update_fields=["workspace_type"])


def workspace_type_resource_to_example(apps, schema_editor):
    """Change the workspace type from "resource" to "example"."""
    Workspace = apps.get_model("anvil_consortium_manager", "Workspace")

    for row in Workspace.objects.filter(workspace_type="resource"):
        row.workspace_type = "example"
        row.save(update_fields=["workspace_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous_workspaces', '0009_rename_example_to_resource_workspace'),
    ]

    operations = [
        migrations.RunPython(workspace_type_example_to_resource, reverse_code=workspace_type_resource_to_example),
    ]
