# Generated by Django 4.2.11 on 2024-03-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miscellaneous_workspaces", "0010_update_workspace_type_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltemplateworkspace",
            name="intended_workspace_type",
        ),
        migrations.RemoveField(
            model_name="templateworkspace",
            name="intended_workspace_type",
        ),
        migrations.AddField(
            model_name="historicaltemplateworkspace",
            name="intended_usage",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateworkspace",
            name="intended_usage",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
