name: Combine PRs

on:
  workflow_dispatch: # allows you to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.2.0
        with:
          labels: combined-pr # Optional: add a label to the combined PR
          ci_required: true # require all checks to pass before combining
          select_label: dependencies # Optional: only combine PRs with this label
          autoclose: false # do not close the source PRs - dependabot should handle it.
