name: Hello world!
on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.COMBINE_PRS_APP_ID }}
          private-key: ${{ secrets.COMBINE_PRS_PRIVATE_KEY }}
      - uses: ./actions/staging-tests
        with:
          token: ${{ steps.app-token.outputs.token }}
