name: Hello world!
on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Use GitHub App Token
        uses: actions/create-github-app-token@eaddb9eb7e4226c68cf4b39f167c83e5bd132b3e # pin@v1.5.1
        id: app-token
        with:
          app-id: ${{ secrets.COMBINE_PRS_APP_ID }} # The ID of the GitHub App
          private-key: ${{ secrets.COMBINE_PRS_PRIVATE_KEY }} # The private key of the GitHub App
